### ISSUE TITLE
Question about 'auth' plugin

### ISSUE THREAD

**Issue by mesqueeb** [steveclarke/quasar-firebase-example#2]
Dear Steve,

Thanks so much for this great library!
I'm a bit confused about this line in the 'auth' plugin:
`let authRequired = to.matched.some(route => route.meta.authRequired)`

1. what is `matched`?
2. what about routes that don't have any `meta` object, won't it give an error: `cannot read authRequired form undefined`?

**Comment by steveclarke** [comment]
`.matched` is a route property. See https://router.vuejs.org/api/#route-object-properties
(An Array containing route records for all nested path segments of the current route.)

It's combined with the JS `.some` method (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) which "tests whether at least one element in the array passes the test implemented by the provided function". From how I understand the method, it won't error if it gets an undefined, it will just not trigger a match.
